default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: newsroom_1_api_development

test:
  <<: *default
  database: newsroom_1_api_test

production:
  <<: *default
  database: newsroom_1_api_production
  username: newsroom_1_api
  password: <%= ENV['NEWSROOM_1_API_DATABASE_PASSWORD'] %>
